substitutions:
  name: "guition-esp32-s3-4848s040"
  friendly_name: "Guition480"
  device_description: "Guition ESP32-S3-4848S040 480*480 Smart Screen"
  project_name: "Guition.ESP32_S3_4848S040"
  project_version: "1.0.0"
  
  lightbulb:     "\U000F0335"
  ceiling_light: "\U000F0769"
  lamp:          "\U000F06B5"
  floor_lamp:    "\U000F08DD"
  string_lights: "\U000F12BA"

  icon_font: light40
  text_font: roboto24  
  screen_hight: '480px'
  screen_width: '480px'
  button_on_color: "Burnt_Sienna"
  button_off_color: "Very_Dark_Gray"  
  icon_on_color: "Yellow"
  icon_off_color: "Gray"
  label_on_color: "White"  
  label_off_color: "Gray"
  button_text_color: "White"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'
  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'
  
  button_1_name: "Local Light"
  button_1_id: local_light
  button_1_icon: $lightbulb
  button_1_device: "internal_relay_1"
  
  button_2_name: "Button 2"
  button_2_id: couch_lamp
  button_2_icon: $lightbulb
  button_2_device: "switch.athom_smart_plug_v3_50ebc0_switch"
  
  # Button 3 is an empty object that requires no settings. It just pushes everything down one button
  
  button_4_name: "RGB light"
  button_4_id: rgb_light
  button_4_icon: $string_lights
  button_4_device: light.athom_rgb_light_d93662_rgb_light_strip
  
globals:
# Keeps track of late night mode for turning off the backlight
  - id: late_night_mode
    type: bool
    restore_value: false
    initial_value: 'false'  

packages:
  base: !include modules/common_base.yaml
  webserver: !include modules/wifi_base.yaml
  hardware: !include modules/hardware/guition-esp32-s3-4848s040.yaml
  colors: !include modules/common/color.yaml
  time: !include modules/lvgl/lvgl_time_sntp.yaml  
  sensors: !include modules/lvgl/lvgl_sensors_base.yaml

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 60s
      - lvgl.widget.hide: boot_screen
 
# -------------------------------------------------------------------------    
# Button state - Update state for Homeassistant objects and internal relays
# ------------------------------------------------------------------------- 

# Internal Relays defined as lights go here
light:
  - !include { file: modules/lvgl/basic_local_relay_button_state.yaml, vars: { id: 1 } }

# Update button state from Home Assistant
text_sensor:
  - !include { file: modules/lvgl/basic_light_switch_button_state.yaml, vars: { id: 2 } }
  - !include { file: modules/lvgl/basic_light_switch_button_state.yaml, vars: { id: 4 } }
  
sensor:  
  - !include { file: modules/lvgl/dimmer_light_switch_state.yaml, vars: { id: 4 } }


#-------------------------------------------
# LVGL pages and Buttons
#-------------------------------------------    

# Wake screen on touch
touchscreen:
  on_touch:
    then:
      - logger.log: "LVGL is active"
      - lvgl.resume:
      - if:   
      # Only turn on baclight and set to 50% if late_night_mode is on
          condition:
            - lambda: |-
                return id(late_night_mode);
          then:      
            - light.turn_on:
                id: display_backlight
                brightness: 50%  

# Main LVGL section
lvgl:
  displays: 
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle: !include { file: modules/lvgl/lvgl_touchscreen_idle.yaml }
    
  theme: !include { file: modules/lvgl/lvgl_theme.yaml }
  page_wrap: true

# Boot Screen  
  top_layer: !include { file: modules/lvgl/boot_screen.yaml, vars: { hight: $screen_hight, width: $screen_width  } }

# Main Page
  pages:
    - id: main_page
      layout: 
        type: flex
        flex_flow: column_wrap
      width: 100%
      bg_color: Black
      bg_opa: cover
      pad_all: 5
      widgets: # Include all the buttons
        - button: !include { file: modules/lvgl/basic_local_relay_button.yaml, vars: { id: 1, hight: $button_height_double } }
        - button: !include { file: modules/lvgl/basic_light_switch_button.yaml, vars: { id: 2, hight: $button_height_single } }
        - button: !include { file: modules/lvgl/transparent_empty_button.yaml, vars: { id: 3, hight: $button_height_single } }
        - button: !include { file: modules/lvgl/dimmer_light_switch_button.yaml, vars: { id: 4, hight: $button_height_double } }        

#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo
    resize: 460x90
    type: RGB565
    use_transparency: true
    
font:
  - file: "gfonts://Roboto"
    id: roboto24
    size: 24
    bpp: 4
    extras:
      # http://materialdesignicons.com/cdn/7.4.47/
      - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
        glyphs: [
          "\U000F004B",
          "\U0000f0ed",
          "\U000F006E",
          "\U000F012C",
          "\U000F179B",
          "\U000F0748",
          "\U000F1A1B",
          "\U000F02DC",
          "\U000F0A02",
          "\U000F035F",
          "\U000F0156",
          "\U000F0C5F",
          "\U000f0084",
          "\U000f0091",
        ]

  # http://materialdesignicons.com/cdn/7.4.47/
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light40
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F0769",  # mdi-ceiling-light
      "\U000F06B5",  # mdi-lamp
      "\U000F08DD",  # mdi-floor-lamp
      "\U000F12BA",  # mdi-string-lights
    ]       
