substitutions:
  name: "guition-esp32-s3-4848s040"
  friendly_name: "Guition480"
  device_description: "Guition ESP32-S3-4848S040 480*480 Smart Screen"
  project_name: "Guition.ESP32_S3_4848S040"
  project_version: "0.9.0"
  
  lightbulb:     "\U000F0335"
  ceiling_light: "\U000F0769"
  lamp:          "\U000F06B5"
  floor_lamp:    "\U000F08DD"
  string_lights: "\U000F12BA"

  icon_font: light40
  text_font: roboto24  
  button_on_color: "0xCC5E14"
  icon_on_color: "0xFFFF00"
  button_off_color: "0x313131"
  icon_off_color: "0xB6B6B6"
  button_hight_single: '109px'
  button_hight_double: '228px'
  
  button_1_name: "Local Light"
  button_1_id: local_light
  button_1_icon: $lightbulb
  button_1_HAdevice: $button_1_id  

logger:
  level: info
  logs:
    i2c.idf: info
    touchscreen: info
    scheduler: none
api:
  encryption:
    key: !secret encryption_key 
ota:
  platform: esphome
web_server:
  port: 80
  version: 3  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password 
  
external_components:
  - source: github://pr#6363 # Previous commit - wont be needed once this code is relaased
    refresh: 10min
    components: [lvgl]

packages:
  common_files:
    url: https://github.com/agillis/esphome-configs
    ref: main # optional
    files: [common/color.yaml,
            guition-esp32-s3-4848s040/common/guition-esp32-s3-4848s040.yaml
    ]    

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time_sync:
      - if:
          condition:
            lambda: 'return id(device_last_restart).state == "";'
          then:
            - text_sensor.template.publish:
                id: device_last_restart
                state: !lambda 'return id(homeassistant_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic
    internal: true

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      entity_category: diagnostic
  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic    
    
 
#-------------------------------------------
# LVGL Buttons
#-------------------------------------------    
lvgl:
  displays:
    - display_id: my_display
  touchscreens:
    - touchscreen_id: my_touchscreen
  on_idle:
    - timeout: 10s
      then:
        - logger.log: idle timeout
        - if:
            condition:
              lvgl.is_idle:
                timeout: 5s
            then:
              - logger.log: LVGL is idle
    - timeout: 15s
      then:
        - logger.log: idle 15s timeout

      #- lvgl.pause:
      #- light.turn_off:
      #    id: display_backlight
      #    transition_length: 5s    

  style_definitions:
    - id: style_line
      line_color: Blue
      line_width: 8
      line_rounded: true
    - id: date_style
      text_font: roboto24
      align: center
      text_color: 0x333333
      bg_opa: cover
      radius: 4
      pad_all: 2

  theme:
    button:
      text_font: roboto24
      scroll_on_focus: true
      group: general
      radius: 25
      width: 150
      height: $button_hight_single
      pad_left: 10px
      pad_top: 10px
      pad_bottom: 10px
      pad_right: 10px
      shadow_width: 0
      bg_color: 0x313131
      text_color: 0xB6B6B6
      checked:
        bg_color: 0xCC5E14
        text_color: 0xB6B6B6

  page_wrap: true
  pages:
    - id: main_page
      skip: true
      layout: 
        type: flex
        flex_flow: column_wrap
      width: 100%
      bg_color: White
      bg_opa: cover
      pad_all: 5
      widgets:
        - button:
            height: $button_hight_double
            checkable: true
            id: lv_button_1
            widgets:
              - label:
                  text_font: $icon_font
                  align: top_left
                  text: $button_1_icon
                  id: lv_button_1_icon
              - label:
                  align: bottom_left
                  text: $button_1_name
            on_click:
                light.toggle: $button_1_HAdevice
              
#-------------------------------------------
# Internal lights
#-------------------------------------------
light:
  - platform: monochromatic
    output: GPIO38
    name: Backlight
    id: backlight
    restore_mode: ALWAYS_ON

  - platform: binary
    output: internal_relay_1
    name: $button_1_name
    id: $button_1_id
    on_turn_on:
      then:
        - lvgl.widget.update:
            id: lv_button_1_icon
            text_color: 0xFFFF00
        - lvgl.widget.update:
            id: lv_button_1
            state:
              checked: true            
    on_turn_off:
      then:
        - lvgl.widget.update:
            id: lv_button_1_icon
            text_color: 0xB6B6B6
        - lvgl.widget.update:
            id: lv_button_1
            state:
              checked: false             

#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
font:
  - file: "gfonts://Roboto"
    id: roboto24
    size: 24
    bpp: 4
    extras:
      # http://materialdesignicons.com/cdn/7.4.47/
      - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
        glyphs: [
          "\U000F004B",
          "\U0000f0ed",
          "\U000F006E",
          "\U000F012C",
          "\U000F179B",
          "\U000F0748",
          "\U000F1A1B",
          "\U000F02DC",
          "\U000F0A02",
          "\U000F035F",
          "\U000F0156",
          "\U000F0C5F",
          "\U000f0084",
          "\U000f0091",
        ]

  # http://materialdesignicons.com/cdn/7.4.47/
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light40
    size: 40
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
      "\U000F0769",  # mdi-ceiling-light
      "\U000F06B5",  # mdi-lamp
      "\U000F08DD",  # mdi-floor-lamp
      "\U000F12BA",  # mdi-string-lights
    ]       
   

    
